name: Sync MLX Files

on:
  push:
    branches: [ master ]
    paths:
      - '**.mlx'

jobs:
  convert-and-sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v2.3.1

      - name: Get Changed MLX Files
        id: get_files
        run: |
          changed_files=$(git diff --name-only HEAD~1 HEAD | grep '\.mlx' || true)
          echo "changed_files=${changed_files}" >> $GITHUB_ENV

      - name: Convert MLX to HTML, PDF, and M
        if: env.changed_files != ''
        run: |
          for file in $changed_files; do
            HTML_FILE_PATH="${file%.mlx}.html"
            PDF_FILE_PATH="${file%.mlx}.pdf"
            M_FILE_PATH="${file%.mlx}.m"
            matlab -batch "matlab.internal.liveeditor.openAndConvert('$file', '$HTML_FILE_PATH')"
            matlab -batch "matlab.internal.liveeditor.openAndConvert('$file', '$PDF_FILE_PATH')"
            matlab -batch "matlab.internal.liveeditor.openAndConvert('$file', '$M_FILE_PATH')"
          done

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Converted MLX files to HTML, PDF, and M formats" || echo "No changes to commit"
          git push
